### PR TITLE
feat(travis-ci): init CI

### PR DESCRIPTION
**Pull request by mickgrz**
You have to register you app on "https://travis-ci.org" before.
Pipeline ran for 1 min 38 sec.

### CODE REVIEW

**Comment by mickgrz** [comment]
this MR is rejected @till  ? Can you update its status ?
Why did u choose an other one ?

**Comment by Cryptophobia** [comment]
Thank you for the PR @mickgrz and following our commit-style guide.

I enabled Travis CI on this repo and will merge this in as a basis for all the other Travis CI PRs.

**Comment by mickgrz** [comment]
thx @till . I'm glad I could help !

**Comment by Cryptophobia** [comment]
@mickgrz , you can look around teamhephy org repos and see if there are other travis ci config files you can add to some other projects. We have around 17 components that build with docker and I'm sure there are other untouched repos.

**Pull request merged**
