### PR TITLE
fix(workflow-cli): ensure `make test` works

### PR DESCRIPTION
**Pull request by till**
- adds missing methods from services support
 - updates dependency in glide

### CODE REVIEW

**Comment by till** [comment]
@Cryptophobia can haz merge? :)

**Comment by till** [comment]
@Cryptophobia can haz merge? :)

**Comment by till** [comment]
@Cryptophobia can haz merge? :)

**Comment by Cryptophobia** [comment]
@till , thank you for fixing! you can haz the merge now. @kingdonb thanks for verifying. @notmaxx and I missed the test.

**Comment by Cryptophobia** [comment]
I created a new issue to remind us to set up travis ci so that we can avoid breaking the tests in the future. :+1:

**Pull request merged**
